# Generated by Django 5.0.8 on 2024-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0003_metrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
    ]
